#!/bin/sh
cd bin
. set-ssh-nodes.sh
. style/print-prompt.sh
. set-network-config.sh
. style/print-prompt.sh
. set-hostname.sh
. style/print-prompt.sh
. set-chrony.sh
. style/print-prompt.sh
. disable_firewall_selinux.sh
. style/print-prompt.sh
. set-local-yum-repos.sh
. style/print-prompt.sh
. install-configure-pacemaker.sh
. style/print-prompt.sh
. install-configure-haproxy.sh
. style/print-prompt.sh
. install-configure-galera.sh
. style/print-prompt.sh
. install-configure-rabbitmq.sh
. style/print-prompt.sh
. install-configure-mongodb.sh
. style/print-prompt.sh
. install-configure-memcached.sh
. style/print-prompt.sh
. install-configure-prerequisites.sh
. style/print-prompt.sh
. install-configure-keystone.sh
. style/print-prompt.sh
. install-configure-glance.sh
. style/print-prompt.sh
. install-configure-nova.sh
. style/print-prompt.sh
. install-configure-neutron.sh
. style/print-prompt.sh
. install-configure-dashboard.sh
. style/print-prompt.sh
. install-configure-cinder.sh
. style/print-prompt.sh
. install-configure-ceilometer.sh
. style/print-prompt.sh
. install-configure-aodh.sh
. style/print-prompt.sh
. install-configure-ceph-deploy.sh
. style/print-prompt.sh
. install-configure-ceph-storage-cluster.sh
. style/print-prompt.sh
. install-configure-ceph-auth-client-key.sh
. style/print-prompt.sh
. install-configure-compute-nodes-services.sh
. restart-pcs-cluster.sh 
